#!/bin/bash
cd ~/thesurvivor2299
wget -pkqm --no-cache --random-wait --no-dns-cache http://thesurvivor2299.com/index.html
wget -pkqm --no-cache --random-wait --no-dns-cache http://thesurvivor2299.com/country.html
wget -pkqm --no-cache --random-wait --no-dns-cache http://thesurvivor2299.com/noentry.html
git add .
git commit . -m "Updated."
git push
